- id: betterleaks
  name: Detect hardcoded secrets
  description: Detect hardcoded secrets using Betterleaks
  entry: betterleaks git --pre-commit --redact --staged --verbose
  language: golang
  pass_filenames: false

- id: betterleaks-docker
  name: Detect hardcoded secrets
  description: Detect hardcoded secrets using Betterleaks
  entry: ghcr.io/betterleaks/betterleaks:latest git --pre-commit --redact --staged --verbose
  language: docker_image
  pass_filenames: false

- id: betterleaks-system
  name: Detect hardcoded secrets
  description: Detect hardcoded secrets using Betterleaks
  entry: betterleaks git --pre-commit --redact --staged --verbose
  language: system
  pass_filenames: false