"""Shared fixtures: a fake repository whose files look like the real ones."""
import json
import tempfile
from pathlib import Path

REGISTRY = {
    "uai-app": {
        "tag": "uai-app-{version}",
        "label": "uai-app",
        "synced": [
            {"kind": "tauri-conf", "path": "crates/uia-app/tauri.conf.json"},
            {"kind": "cargo-toml", "path": "crates/uia-app/Cargo.toml"},
            {"kind": "cargo-lock", "path": "Cargo.lock"},
        ],
        "code_paths": ["crates/**", "src/**", "Cargo.toml", "Cargo.lock", "package.json"],
        "ignore_paths": ["docs/**", "**/*.md", ".github/**", "scripts/**"],
    }
}

TAURI = """{
  "$schema": "https://schema.tauri.app/config/2",
  "productName": "uia",
  "version": "@V@",
  "bundle": {
    "windows": { "wix": { "version": "9.9.9" } }
  },
  "plugins": {
    "deep-link": {
        "version": "decoy"
    }
  }
}
"""

CARGO_TOML = """[package]
name = "uia-app"
version = "@V@"  # kept in step by scripts/release
edition = "2021"

[dependencies]
serde = { version = "1" }

[dependencies.tauri]
version = "2.11.5"
"""

CARGO_LOCK = """# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "serde"
version = "1.0.1"

[[package]]
name = "uia-app"
version = "@V@"
dependencies = [
 "serde",
]
"""

GOOD_BODY = """## Summary

Adds a thing.

## Release note

Adds a thing users asked for.

## Testing

Ran the suite.
"""


def make_repo(version="0.1.1", root=None) -> Path:
    root = Path(root or tempfile.mkdtemp())
    (root / ".github").mkdir(parents=True, exist_ok=True)
    (root / "crates/uia-app").mkdir(parents=True, exist_ok=True)
    (root / ".github/release-components.json").write_text(json.dumps(REGISTRY, indent=2))
    (root / "version.json").write_text(json.dumps({"uai-app": version}) + "\n")
    (root / "crates/uia-app/tauri.conf.json").write_text(TAURI.replace("@V@", version))
    (root / "crates/uia-app/Cargo.toml").write_text(CARGO_TOML.replace("@V@", version))
    (root / "Cargo.lock").write_text(CARGO_LOCK.replace("@V@", version))
    return root


def load_registry_from(root):
    from release.registry import load_registry

    return load_registry(Path(root) / ".github/release-components.json")


def two_component_registry(root=None):
    """The uai-app registry plus a uai-mobile that owns mobile/**."""
    import json as _json
    root = make_repo(root=root)
    both = _json.loads(_json.dumps(REGISTRY))
    both["uai-mobile"] = {
        "tag": "uai-mobile-{version}",
        "label": "uai-mobile",
        "synced": [],
        "code_paths": ["mobile/**"],
        "ignore_paths": [],
    }
    (root / ".github/release-components.json").write_text(_json.dumps(both))
    return load_registry_from(root)
